server:
  port: 8086
dubbo:
  application:
    name: cart-service-provider
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    port: 28005
spring:
  redis:
    host: 192.168.199.128
    port: 6379