server:
  port: 8083
spring:
  application:
    name: spring-shop-item-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dubbo-demo?serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
template:
  path: G:\\items\\
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/