server:
  port: 9091
dubbo:
  application:
    name: product-service-background-consumer
  registry:
    address: zookeeper://127.0.0.1:2181
spring:
  thymeleaf:
    cache: false
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /test
fdfs:
  so-timeout: 1500  #读取超时时间
  connect-timeout: 600  #连接超时时间
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 192.168.199.128:22122
image:
  path: 192.168.199.128:8888